export const SET_USER = 'SET_USER'
export const TOGGLE_OPEN_MODAL_PROFILE = 'TOGGLE_OPEN_MODAL_PROFILE'
export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE'
export const TOGGLE_IS_LOADER = 'TOGGLE_IS_LOADER'

